categories = [
    {"name": "Restaurant", "description": "Establishments serving food and beverages."},
    {"name": "Retail", "description": "Stores selling goods and merchandise."},
    {
        "name": "Health & Wellness",
        "description": "Services related to health and personal well-being.",
    },
    {
        "name": "Education",
        "description": "Institutions providing educational services.",
    },
    {"name": "Technology", "description": "Businesses in the tech industry."},
    {"name": "Finance", "description": "Companies offering financial services."},
    {
        "name": "Entertainment",
        "description": "Businesses providing entertainment services.",
    },
    {
        "name": "Real Estate",
        "description": "Companies dealing with property and real estate.",
    },
    {
        "name": "Travel & Tourism",
        "description": "Services related to travel and tourism.",
    },
    {
        "name": "Automotive",
        "description": "Businesses related to vehicles and automotive services.",
    },
]

restaurants = [
    {
        "name": "Lagos Taste Delight",
        "description": "Lagos Taste Delight offers a variety of local and continental dishes in a cozy environment with excellent customer service.",
        "address": "45 Adeola Odeku Street, Victoria Island",
        "city": "Lagos",
        "state": "Lagos",
        "zip_code": "101241",
        "phone_number": "08012345678",
        "website": "http://lagostastedelight.com",
    },
    {
        "name": "Abuja Gourmet Hub",
        "description": "Abuja Gourmet Hub is known for its exquisite dining experience, offering a fusion of Nigerian and international cuisines.",
        "address": "12 Aminu Kano Crescent, Wuse 2",
        "city": "Abuja",
        "state": "FCT",
        "zip_code": "900288",
        "phone_number": "08023456789",
        "website": "http://abujagourmethub.com",
    },
    {
        "name": "Ibadan Flavors",
        "description": "Ibadan Flavors serves a variety of traditional and modern dishes, making it a popular spot for both locals and visitors.",
        "address": "23 Bodija Road, Bodija",
        "city": "Ibadan",
        "state": "Oyo",
        "zip_code": "200285",
        "phone_number": "08034567890",
        "website": "http://ibadanflavors.com",
    },
    {
        "name": "Port Harcourt Eateries",
        "description": "Port Harcourt Eateries offers a rich menu featuring fresh seafood and local delicacies in a vibrant atmosphere.",
        "address": "30 Azikiwe Road, Diobu",
        "city": "Port Harcourt",
        "state": "Rivers",
        "zip_code": "500262",
        "phone_number": "08045678901",
        "website": "http://phceateries.com",
    },
    {
        "name": "Onitsha Savories",
        "description": "Onitsha Savories is a family-friendly restaurant offering a wide range of Nigerian and continental dishes.",
        "address": "18 Old Market Road, Odoakpu",
        "city": "Onitsha",
        "state": "Anambra",
        "zip_code": "434106",
        "phone_number": "08056789012",
        "website": "http://onitshasavories.com",
    },
    {
        "name": "Aba Dining Palace",
        "description": "Aba Dining Palace is renowned for its delicious traditional meals and contemporary dishes, served in a royal setting.",
        "address": "27 Brass Road, Aba",
        "city": "Aba",
        "state": "Abia",
        "zip_code": "450271",
        "phone_number": "08067890123",
        "website": "http://abadiningpalace.com",
    },
    {
        "name": "Enugu Feasts",
        "description": "Enugu Feasts provides an exceptional dining experience with a menu that highlights the best of Nigerian cuisine.",
        "address": "9 Ogui Road, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "zip_code": "400102",
        "phone_number": "08078901234",
        "website": "http://enugufeasts.com",
    },
    {
        "name": "Sokoto Bites",
        "description": "Sokoto Bites specializes in local dishes from Northern Nigeria, served in a relaxed and inviting atmosphere.",
        "address": "14 Ahmadu Bello Way, Sokoto",
        "city": "Sokoto",
        "state": "Sokoto",
        "zip_code": "840101",
        "phone_number": "08089012345",
        "website": "http://sokotobites.com",
    },
    {
        "name": "Kano Culinary Corner",
        "description": "Kano Culinary Corner offers a diverse menu of both traditional Nigerian and international dishes in an elegant setting.",
        "address": "22 Bompai Road, Kano",
        "city": "Kano",
        "state": "Kano",
        "zip_code": "700213",
        "phone_number": "08090123456",
        "website": "http://kanoculinarycorner.com",
    },
    {
        "name": "Kaduna Kitchen",
        "description": "Kaduna Kitchen is known for its flavorful dishes and warm hospitality, making it a favorite among locals.",
        "address": "6 Tafawa Balewa Way, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "zip_code": "800282",
        "phone_number": "08001234567",
        "website": "http://kadunakitchen.com",
    },
    {
        "name": "Benin Royal Cuisine",
        "description": "Benin Royal Cuisine offers an extensive menu of local delicacies and international dishes in a regal atmosphere.",
        "address": "15 Airport Road, Benin City",
        "city": "Benin",
        "state": "Edo",
        "zip_code": "300223",
        "phone_number": "08021345678",
        "website": "http://beninroyalcuisine.com",
    },
    {
        "name": "Bauchi Flavors",
        "description": "Bauchi Flavors is known for its delicious traditional meals and contemporary dishes, served in a cozy setting.",
        "address": "10 Gombe Road, Bauchi",
        "city": "Bauchi",
        "state": "Bauchi",
        "zip_code": "740214",
        "phone_number": "08032456789",
        "website": "http://bauchiflavors.com",
    },
    {
        "name": "Uyo Delights",
        "description": "Uyo Delights offers a variety of local and continental dishes in a modern and stylish environment.",
        "address": "20 Oron Road, Uyo",
        "city": "Uyo",
        "state": "Akwa Ibom",
        "zip_code": "520262",
        "phone_number": "08043567890",
        "website": "http://uyodelights.com",
    },
    {
        "name": "Warri Eats",
        "description": "Warri Eats provides an exceptional dining experience with a menu that highlights the best of Nigerian cuisine.",
        "address": "35 Effurun Road, Warri",
        "city": "Warri",
        "state": "Delta",
        "zip_code": "320242",
        "phone_number": "08054678901",
        "website": "http://warrieats.com",
    },
    {
        "name": "Jos Savories",
        "description": "Jos Savories is a family-friendly restaurant offering a wide range of Nigerian and continental dishes.",
        "address": "18 Ahmadu Bello Way, Jos",
        "city": "Jos",
        "state": "Plateau",
        "zip_code": "930101",
        "phone_number": "08065789012",
        "website": "http://jossavories.com",
    },
    {
        "name": "Ilorin Bites",
        "description": "Ilorin Bites specializes in local dishes from Western Nigeria, served in a relaxed and inviting atmosphere.",
        "address": "22 Ibrahim Taiwo Road, Ilorin",
        "city": "Ilorin",
        "state": "Kwara",
        "zip_code": "240101",
        "phone_number": "08076890123",
        "website": "http://ilorinbites.com",
    },
    {
        "name": "Akure Gourmet",
        "description": "Akure Gourmet offers a diverse menu of both traditional Nigerian and international dishes in an elegant setting.",
        "address": "11 Oba Adesida Road, Akure",
        "city": "Akure",
        "state": "Ondo",
        "zip_code": "340271",
        "phone_number": "08087901234",
        "website": "http://akuregourmet.com",
    },
    {
        "name": "Owerri Flavors",
        "description": "Owerri Flavors is known for its flavorful dishes and warm hospitality, making it a favorite among locals.",
        "address": "14 Tetlow Road, Owerri",
        "city": "Owerri",
        "state": "Imo",
        "zip_code": "460251",
        "phone_number": "08098012345",
        "website": "http://owerriflavors.com",
    },
    {
        "name": "Abeokuta Kitchen",
        "description": "Abeokuta Kitchen offers an extensive menu of local delicacies and international dishes in a cozy atmosphere.",
        "address": "25 Abiola Way, Abeokuta",
        "city": "Abeokuta",
        "state": "Ogun",
        "zip_code": "110232",
        "phone_number": "08009123456",
        "website": "http://abeokutakitchen.com",
    },
    {
        "name": "Calabar Feast",
        "description": "Calabar Feast provides an exceptional dining experience with a menu that highlights the best of Nigerian cuisine.",
        "address": "30 Marian Road, Calabar",
        "city": "Calabar",
        "state": "Cross River",
        "zip_code": "540213",
        "phone_number": "08010234567",
        "website": "http://calabarfeast.com",
    },
    {
        "name": "Maiduguri Savories",
        "description": "Maiduguri Savories is known for its delicious traditional meals and contemporary dishes, served in a modern setting.",
        "address": "18 Baga Road, Maiduguri",
        "city": "Maiduguri",
        "state": "Borno",
        "zip_code": "600282",
        "phone_number": "08021345678",
        "website": "http://maidugurisavories.com",
    },
    {
        "name": "Makurdi Delights",
        "description": "Makurdi Delights offers a variety of local and continental dishes in a stylish and comfortable environment.",
        "address": "12 Gboko Road, Makurdi",
        "city": "Makurdi",
        "state": "Benue",
        "zip_code": "970101",
        "phone_number": "08032456789",
        "website": "http://makurdidelights.com",
    },
    {
        "name": "Ado-Ekiti Bites",
        "description": "Ado-Ekiti Bites specializes in local dishes from Southwestern Nigeria, served in a relaxed and inviting atmosphere.",
        "address": "22 Iworoko Road, Ado-Ekiti",
        "city": "Ado-Ekiti",
        "state": "Ekiti",
        "zip_code": "360101",
        "phone_number": "08043567890",
        "website": "http://adoekitibites.com",
    },
    {
        "name": "Katsina Cuisine",
        "description": "Katsina Cuisine offers an extensive menu of local delicacies and international dishes in a cozy atmosphere.",
        "address": "14 Hassan Usman Katsina Road, Katsina",
        "city": "Katsina",
        "state": "Katsina",
        "zip_code": "820101",
        "phone_number": "08054678901",
        "website": "http://katsinacuisine.com",
    },
    {
        "name": "Minna Feasts",
        "description": "Minna Feasts provides an exceptional dining experience with a menu that highlights the best of Nigerian cuisine.",
        "address": "25 Paiko Road, Minna",
        "city": "Minna",
        "state": "Niger",
        "zip_code": "920101",
        "phone_number": "08065789012",
        "website": "http://minnafeasts.com",
    },
    {
        "name": "Yola Delights",
        "description": "Yola Delights is known for its delicious traditional meals and contemporary dishes, served in a modern setting.",
        "address": "10 Numan Road, Yola",
        "city": "Yola",
        "state": "Adamawa",
        "zip_code": "640101",
        "phone_number": "08076890123",
        "website": "http://yoladelights.com",
    },
    {
        "name": "Awka Bites",
        "description": "Awka Bites specializes in local dishes from Southeastern Nigeria, served in a relaxed and inviting atmosphere.",
        "address": "14 Zik Avenue, Awka",
        "city": "Awka",
        "state": "Anambra",
        "zip_code": "420101",
        "phone_number": "08087901234",
        "website": "http://awkabites.com",
    },
    {
        "name": "Gombe Gourmet",
        "description": "Gombe Gourmet offers a diverse menu of both traditional Nigerian and international dishes in an elegant setting.",
        "address": "18 Bauchi Road, Gombe",
        "city": "Gombe",
        "state": "Gombe",
        "zip_code": "760101",
        "phone_number": "08098012345",
        "website": "http://gombegourmet.com",
    },
    {
        "name": "Birnin Kebbi Kitchen",
        "description": "Birnin Kebbi Kitchen offers an extensive menu of local delicacies and international dishes in a cozy atmosphere.",
        "address": "20 Ahmadu Bello Way, Birnin Kebbi",
        "city": "Birnin Kebbi",
        "state": "Kebbi",
        "zip_code": "860101",
        "phone_number": "08009123456",
        "website": "http://birninkebbikitchen.com",
    },
    {
        "name": "Lagos Gourmet Haven",
        "description": "Lagos Gourmet Haven offers a blend of traditional and international cuisines in a stylish and comfortable setting.",
        "address": "50 Admiralty Way, Lekki Phase 1",
        "city": "Lagos",
        "state": "Lagos",
        "zip_code": "105102",
        "phone_number": "08012345679",
        "website": "http://lagosgourmethaven.com",
    },
    {
        "name": "Abuja Culinary Delights",
        "description": "Abuja Culinary Delights is a fine dining restaurant known for its exquisite dishes and exceptional service.",
        "address": "25 Gana Street, Maitama",
        "city": "Abuja",
        "state": "FCT",
        "zip_code": "900271",
        "phone_number": "08023456790",
        "website": "http://abujaculinarydelights.com",
    },
    {
        "name": "Ibadan Taste Buds",
        "description": "Ibadan Taste Buds offers a variety of delicious meals, from local delicacies to continental dishes, in a cozy environment.",
        "address": "30 Ring Road, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "zip_code": "200212",
        "phone_number": "08034567891",
        "website": "http://ibadantastebuds.com",
    },
    {
        "name": "Port Harcourt Bites",
        "description": "Port Harcourt Bites is a popular spot for seafood lovers, offering fresh and tasty dishes in a vibrant setting.",
        "address": "28 Aba Road, GRA Phase 2",
        "city": "Port Harcourt",
        "state": "Rivers",
        "zip_code": "500271",
        "phone_number": "08045678902",
        "website": "http://phcbites.com",
    },
    {
        "name": "Enugu Dining Experience",
        "description": "Enugu Dining Experience provides an exceptional range of Nigerian and international dishes, served in an elegant atmosphere.",
        "address": "35 Independence Layout, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "zip_code": "400271",
        "phone_number": "08056789013",
        "website": "http://enugudiningexperience.com",
    },
    {
        "name": "Kano Food Palace",
        "description": "Kano Food Palace offers a wide range of local and continental dishes, served in a luxurious and comfortable setting.",
        "address": "40 Murtala Mohammed Way, Kano",
        "city": "Kano",
        "state": "Kano",
        "zip_code": "700282",
        "phone_number": "08067890124",
        "website": "http://kanofoodpalace.com",
    },
    {
        "name": "Benin Dining Hub",
        "description": "Benin Dining Hub is known for its delicious traditional meals and contemporary dishes, served in a modern setting.",
        "address": "22 Akpakpava Road, Benin City",
        "city": "Benin",
        "state": "Edo",
        "zip_code": "300282",
        "phone_number": "08078901235",
        "website": "http://benindininghub.com",
    },
    {
        "name": "Onitsha Gourmet Point",
        "description": "Onitsha Gourmet Point offers an exceptional range of local and international dishes in a stylish and comfortable environment.",
        "address": "40 Awka Road, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "zip_code": "434102",
        "phone_number": "08089012346",
        "website": "http://onitshagourmetpoint.com",
    },
    {
        "name": "Kaduna Delights",
        "description": "Kaduna Delights serves a variety of traditional and modern dishes, making it a popular spot for both locals and visitors.",
        "address": "55 Ahmadu Bello Way, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "zip_code": "800212",
        "phone_number": "08090123457",
        "website": "http://kadunadelights.com",
    },
    {
        "name": "Aba Culinary Hub",
        "description": "Aba Culinary Hub offers a wide range of Nigerian and international dishes in a cozy and inviting atmosphere.",
        "address": "12 Factory Road, Aba",
        "city": "Aba",
        "state": "Abia",
        "zip_code": "450211",
        "phone_number": "08001234568",
        "website": "http://abaculinaryhub.com",
    },
    {
        "name": "Lagos Spice Garden",
        "description": "Lagos Spice Garden offers a vibrant dining experience with an extensive menu of spicy local and international dishes.",
        "address": "75 Victoria Island, Lagos",
        "city": "Lagos",
        "state": "Lagos",
        "zip_code": "101241",
        "phone_number": "08022345678",
        "website": "http://lagosspicegarden.com",
    },
    {
        "name": "Abuja Gourmet Spot",
        "description": "Abuja Gourmet Spot is a high-end restaurant known for its gourmet meals and exquisite ambiance.",
        "address": "100 Aminu Kano Crescent, Wuse 2",
        "city": "Abuja",
        "state": "FCT",
        "zip_code": "900288",
        "phone_number": "08033456789",
        "website": "http://abujagourmetspot.com",
    },
    {
        "name": "Ibadan Fusion",
        "description": "Ibadan Fusion serves a blend of traditional and contemporary dishes in a relaxed, stylish environment.",
        "address": "60 Bodija, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "zip_code": "200252",
        "phone_number": "08044567890",
        "website": "http://ibadanfusion.com",
    },
    {
        "name": "Port Harcourt Delicacies",
        "description": "Port Harcourt Delicacies specializes in seafood and a variety of local and international dishes in a cozy setting.",
        "address": "45 Olu Obasanjo Road, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "zip_code": "500281",
        "phone_number": "08055678901",
        "website": "http://phcdelicacies.com",
    },
    {
        "name": "Enugu Delight",
        "description": "Enugu Delight offers a diverse menu of delicious meals, from traditional Nigerian dishes to international cuisine.",
        "address": "27 Zik Avenue, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "zip_code": "400282",
        "phone_number": "08066789012",
        "website": "http://enugudelight.com",
    },
    {
        "name": "Kano Gourmet Kitchen",
        "description": "Kano Gourmet Kitchen provides a luxurious dining experience with a menu featuring local and international delicacies.",
        "address": "80 Zaria Road, Kano",
        "city": "Kano",
        "state": "Kano",
        "zip_code": "700291",
        "phone_number": "08077890123",
        "website": "http://kanogourmetkitchen.com",
    },
    {
        "name": "Benin Culinary Oasis",
        "description": "Benin Culinary Oasis is known for its exceptional range of traditional and contemporary dishes, served in a modern setting.",
        "address": "65 Sapele Road, Benin City",
        "city": "Benin",
        "state": "Edo",
        "zip_code": "300282",
        "phone_number": "08088901234",
        "website": "http://beninculinaryoasis.com",
    },
    {
        "name": "Onitsha Savory Spot",
        "description": "Onitsha Savory Spot offers a diverse menu of local and international dishes in a stylish and comfortable environment.",
        "address": "55 Old Market Road, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "zip_code": "434104",
        "phone_number": "08099012345",
        "website": "http://onitshasavoryspot.com",
    },
    {
        "name": "Kaduna Feast",
        "description": "Kaduna Feast is a popular restaurant offering a wide range of traditional and contemporary dishes in a vibrant setting.",
        "address": "72 Independence Way, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "zip_code": "800242",
        "phone_number": "08010123456",
        "website": "http://kadunafeast.com",
    },
    {
        "name": "Aba Gourmet Place",
        "description": "Aba Gourmet Place offers a unique dining experience with an extensive menu of local and international delicacies.",
        "address": "37 Aba-Owerri Road, Aba",
        "city": "Aba",
        "state": "Abia",
        "zip_code": "450212",
        "phone_number": "08021234567",
        "website": "http://abagourmetplace.com",
    },
    {
        "name": "Lagos Delights",
        "description": "Lagos Delights is a cozy restaurant offering a fusion of local and continental cuisines in a relaxed environment.",
        "address": "20 Ikoyi Crescent, Ikoyi",
        "city": "Lagos",
        "state": "Lagos",
        "zip_code": "101233",
        "phone_number": "08087654321",
        "website": "http://lagosdelights.com",
    },
    {
        "name": "Abuja Epicurean",
        "description": "Abuja Epicurean is a fine dining restaurant known for its exquisite menu and elegant ambiance, perfect for special occasions.",
        "address": "15 Jabi Lake Mall, Jabi",
        "city": "Abuja",
        "state": "FCT",
        "zip_code": "900245",
        "phone_number": "08098765432",
        "website": "http://abujaepicurean.com",
    },
    {
        "name": "Ibadan Flavors",
        "description": "Ibadan Flavors offers a wide variety of delicious dishes, from traditional Nigerian meals to international favorites.",
        "address": "18 Agodi Gardens, Ibadan",
        "city": "Ibadan",
        "state": "Oyo",
        "zip_code": "200271",
        "phone_number": "08087656789",
        "website": "http://ibadanflavors.com",
    },
    {
        "name": "Port Harcourt Spice Hub",
        "description": "Port Harcourt Spice Hub is a popular destination for spicy and flavorful meals, served in a vibrant and welcoming atmosphere.",
        "address": "22 Peter Odili Road, Port Harcourt",
        "city": "Port Harcourt",
        "state": "Rivers",
        "zip_code": "500264",
        "phone_number": "08099876543",
        "website": "http://phcspicehub.com",
    },
    {
        "name": "Enugu Gourmet Heaven",
        "description": "Enugu Gourmet Heaven offers an extensive menu of gourmet dishes, blending local flavors with international cuisine.",
        "address": "10 Ogui Road, Enugu",
        "city": "Enugu",
        "state": "Enugu",
        "zip_code": "400262",
        "phone_number": "08088765432",
        "website": "http://enugugourmetheaven.com",
    },
    {
        "name": "Kano Savory Kitchen",
        "description": "Kano Savory Kitchen is a top choice for food lovers, offering a diverse menu of tasty dishes in a cozy setting.",
        "address": "50 Bompai Road, Kano",
        "city": "Kano",
        "state": "Kano",
        "zip_code": "700263",
        "phone_number": "08099876654",
        "website": "http://kanosavorykitchen.com",
    },
    {
        "name": "Benin Flavor House",
        "description": "Benin Flavor House serves an array of traditional and contemporary meals, making it a favorite spot for locals and tourists.",
        "address": "30 Airport Road, Benin City",
        "city": "Benin",
        "state": "Edo",
        "zip_code": "300263",
        "phone_number": "08087766543",
        "website": "http://beninflavorhouse.com",
    },
    {
        "name": "Onitsha Taste Haven",
        "description": "Onitsha Taste Haven offers a delightful dining experience with a wide range of delicious meals in a stylish setting.",
        "address": "15 New Market Road, Onitsha",
        "city": "Onitsha",
        "state": "Anambra",
        "zip_code": "434115",
        "phone_number": "08088776554",
        "website": "http://onitshatastehaven.com",
    },
    {
        "name": "Kaduna Cuisine Delight",
        "description": "Kaduna Cuisine Delight provides a variety of tasty dishes, from local specialties to international cuisines, in a friendly environment.",
        "address": "45 Ali Akilu Road, Kaduna",
        "city": "Kaduna",
        "state": "Kaduna",
        "zip_code": "800221",
        "phone_number": "08099777665",
        "website": "http://kadunacuisinedelight.com",
    },
    {
        "name": "Aba Dining Lounge",
        "description": "Aba Dining Lounge is a premier restaurant offering an extensive menu of both local and continental dishes in a chic ambiance.",
        "address": "25 Eziukwu Road, Aba",
        "city": "Aba",
        "state": "Abia",
        "zip_code": "450215",
        "phone_number": "08088777666",
        "website": "http://abadininglounge.com",
    },
]
