"""IsBusiness is not nullable, default to false

Revision ID: 15e7471ffa36
Revises: 885089bbcc90
Create Date: 2024-07-03 07:56:22.867239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e7471ffa36'
down_revision = '885089bbcc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_business',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_business',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
